import jsPDF from "jspdf";
import { ResumeData } from "./pdfGenerator";

export interface OptimizationReportData {
  resumeData: ResumeData;
  jobDescription: string;
  analysis: {
    summary?: {
      current_assessment: string;
      improved_version: string;
      key_changes: string[];
    };
    experience?: Array<{
      role: string;
      current_assessment: string;
      improved_bullets: string[];
      missing_keywords_to_add: string[];
    }>;
    skills?: {
      keep: string[];
      add: string[];
      remove: string[];
      reorganized: string;
    };
    keywords?: {
      found_in_resume: string[];
      missing_critical: string[];
      missing_preferred: string[];
    };
    overall_tips?: string[];
  };
  appliedChanges: Set<string>;
  atsScore?: number;
}

const COLORS = {
  primary: "#2b3f8e",
  accent: "#0ea573",
  destructive: "#e53e3e",
  warning: "#d69e2e",
  dark: "#1a202c",
  muted: "#718096",
  light: "#e2e8f0",
  bg: "#f7fafc",
  white: "#ffffff",
};

export const generateOptimizationReport = (data: OptimizationReportData): jsPDF => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const ml = 15; // margin left
  const mr = 15;
  const cw = pageWidth - ml - mr; // content width
  const bottomMargin = 20;
  let y = 15;

  const checkPage = (needed: number) => {
    if (y + needed > pageHeight - bottomMargin) {
      addFooter();
      doc.addPage();
      y = 15;
    }
  };

  let pageNum = 1;
  const addFooter = () => {
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.muted);
    doc.text(`Generated by ATSFy — Page ${pageNum}`, pageWidth / 2, pageHeight - 8, { align: "center" });
    doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageWidth - mr, pageHeight - 8, { align: "right" });
    pageNum++;
  };

  const addWrapped = (text: string, x: number, maxW: number, lh: number = 4.5): void => {
    const lines = doc.splitTextToSize(text, maxW);
    lines.forEach((line: string) => {
      checkPage(lh);
      doc.text(line, x, y);
      y += lh;
    });
  };

  const addSectionTitle = (title: string) => {
    checkPage(12);
    y += 4;
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.primary);
    doc.text(title, ml, y);
    y += 2;
    doc.setDrawColor(COLORS.primary);
    doc.setLineWidth(0.6);
    doc.line(ml, y, pageWidth - mr, y);
    y += 5;
  };

  const addSubTitle = (title: string) => {
    checkPage(8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.dark);
    doc.text(title, ml, y);
    y += 4.5;
  };

  const addLabel = (label: string, color: string = COLORS.muted) => {
    checkPage(6);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(color);
    doc.text(label.toUpperCase(), ml, y);
    y += 3.5;
  };

  const addBody = (text: string, indent: number = 0) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.dark);
    addWrapped(text, ml + indent, cw - indent, 4);
  };

  const addBullet = (text: string, indent: number = 4) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.dark);
    const bulletText = `•  ${text}`;
    addWrapped(bulletText, ml + indent, cw - indent - 2, 4);
  };

  const addTag = (text: string, x: number, bgColor: string, textColor: string): number => {
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    const tw = doc.getTextWidth(text) + 4;
    checkPage(6);
    doc.setFillColor(bgColor);
    doc.roundedRect(x, y - 3, tw, 5, 1.5, 1.5, "F");
    doc.setTextColor(textColor);
    doc.text(text, x + 2, y);
    return tw + 2;
  };

  // ============================
  // COVER PAGE
  // ============================
  // Header bar
  doc.setFillColor(COLORS.primary);
  doc.rect(0, 0, pageWidth, 45, "F");

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.white);
  doc.text("Resume Optimization Report", pageWidth / 2, 22, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor("#c3cfe2");
  doc.text("Detailed Analysis & Recommendations", pageWidth / 2, 32, { align: "center" });

  y = 55;

  // Candidate info box
  doc.setFillColor(COLORS.bg);
  doc.roundedRect(ml, y, cw, 28, 3, 3, "F");
  doc.setDrawColor(COLORS.light);
  doc.roundedRect(ml, y, cw, 28, 3, 3, "S");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.dark);
  doc.text("Candidate", ml + 5, y + 8);
  doc.setFontSize(14);
  doc.text(data.resumeData.personalInfo.fullName || "Not Provided", ml + 5, y + 16);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.muted);
  const contactLine = [data.resumeData.personalInfo.email, data.resumeData.personalInfo.phone, data.resumeData.personalInfo.location].filter(Boolean).join("  |  ");
  doc.text(contactLine, ml + 5, y + 22);

  // ATS score on the right
  if (data.atsScore !== undefined) {
    const scoreX = pageWidth - mr - 25;
    const scoreColor = data.atsScore >= 85 ? COLORS.accent : data.atsScore >= 70 ? COLORS.primary : data.atsScore >= 50 ? COLORS.warning : COLORS.destructive;
    doc.setFillColor(scoreColor);
    doc.circle(scoreX + 10, y + 14, 10, "F");
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.white);
    doc.text(`${data.atsScore}%`, scoreX + 10, y + 16, { align: "center" });
    doc.setFontSize(7);
    doc.setTextColor(COLORS.muted);
    doc.text("ATS Score", scoreX + 10, y + 27, { align: "center" });
  }

  y += 36;

  // Report date
  doc.setFontSize(8);
  doc.setTextColor(COLORS.muted);
  doc.text(`Report generated: ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}`, ml, y);
  y += 4;
  
  const appliedCount = data.appliedChanges.size;
  const totalSections = (data.analysis.summary ? 1 : 0) + (data.analysis.experience?.length || 0) + (data.analysis.skills ? 1 : 0);
  doc.text(`Changes applied: ${appliedCount} of ${totalSections} sections`, ml, y);
  y += 8;

  // Executive Summary
  addSectionTitle("EXECUTIVE SUMMARY");
  addBody(
    `This report provides a comprehensive analysis of ${data.resumeData.personalInfo.fullName || "the candidate"}'s resume against the target job description. ` +
    `The analysis covers professional summary optimization, experience bullet improvements using the XYZ impact formula, ` +
    `skills gap identification, and keyword coverage mapping. Each section includes specific, actionable recommendations ` +
    `directly tied to the job requirements.`
  );
  y += 2;

  // Job Description excerpt
  if (data.jobDescription) {
    addSectionTitle("TARGET JOB DESCRIPTION");
    const jdPreview = data.jobDescription.length > 800 
      ? data.jobDescription.substring(0, 800) + "..."
      : data.jobDescription;
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(COLORS.muted);
    addWrapped(jdPreview, ml, cw, 3.5);
    y += 2;
  }

  // ============================
  // PROFESSIONAL SUMMARY ANALYSIS
  // ============================
  if (data.analysis.summary) {
    addSectionTitle("1. PROFESSIONAL SUMMARY — ANALYSIS & IMPROVEMENT");

    addLabel("CURRENT ASSESSMENT", COLORS.destructive);
    addBody(data.analysis.summary.current_assessment);
    y += 3;

    addLabel("OPTIMIZED VERSION (TAILORED TO JD)", COLORS.accent);
    addBody(data.analysis.summary.improved_version);
    y += 3;

    if (data.analysis.summary.key_changes?.length > 0) {
      addLabel("KEY CHANGES MADE");
      data.analysis.summary.key_changes.forEach(change => {
        addBullet(change);
      });
    }
    y += 2;

    // Applied status
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    if (data.appliedChanges.has("summary")) {
      doc.setTextColor(COLORS.accent);
      doc.text("✓ APPLIED TO RESUME", ml, y);
    } else {
      doc.setTextColor(COLORS.warning);
      doc.text("○ NOT YET APPLIED", ml, y);
    }
    y += 5;
  }

  // ============================
  // EXPERIENCE ANALYSIS
  // ============================
  if (data.analysis.experience && data.analysis.experience.length > 0) {
    addSectionTitle("2. WORK EXPERIENCE — BULLET-BY-BULLET IMPROVEMENTS");

    data.analysis.experience.forEach((exp, i) => {
      checkPage(15);
      addSubTitle(`${i + 1}. ${exp.role}`);

      addLabel("ASSESSMENT", COLORS.muted);
      addBody(exp.current_assessment, 2);
      y += 2;

      if (exp.improved_bullets?.length > 0) {
        addLabel("IMPROVED BULLETS (XYZ FORMULA)", COLORS.accent);
        exp.improved_bullets.forEach(bullet => {
          const clean = bullet.replace(/^[•\-]\s*/, "");
          addBullet(clean, 4);
        });
        y += 2;
      }

      if (exp.missing_keywords_to_add?.length > 0) {
        addLabel("MISSING KEYWORDS TO INCORPORATE", COLORS.destructive);
        let tagX = ml + 2;
        const maxX = pageWidth - mr;
        checkPage(8);
        exp.missing_keywords_to_add.forEach(kw => {
          const kwWidth = doc.getTextWidth(kw) + 6;
          if (tagX + kwWidth > maxX) {
            y += 6;
            tagX = ml + 2;
          }
          tagX += addTag(kw, tagX, "#fed7d7", COLORS.destructive);
        });
        y += 6;
      }

      // Applied status
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      if (data.appliedChanges.has(`exp-${i}`)) {
        doc.setTextColor(COLORS.accent);
        doc.text("✓ APPLIED", ml + 2, y);
      } else {
        doc.setTextColor(COLORS.warning);
        doc.text("○ NOT APPLIED", ml + 2, y);
      }
      y += 6;
    });
  }

  // ============================
  // SKILLS OPTIMIZATION
  // ============================
  if (data.analysis.skills) {
    addSectionTitle("3. SKILLS OPTIMIZATION");

    if (data.analysis.skills.keep?.length > 0) {
      addLabel("✓ KEEP — MATCHES JOB DESCRIPTION", COLORS.accent);
      let tagX = ml + 2;
      checkPage(8);
      data.analysis.skills.keep.forEach(s => {
        const sw = doc.getTextWidth(s) + 6;
        if (tagX + sw > pageWidth - mr) { y += 6; tagX = ml + 2; }
        tagX += addTag(s, tagX, "#c6f6d5", "#276749");
      });
      y += 7;
    }

    if (data.analysis.skills.add?.length > 0) {
      addLabel("+ ADD — FROM JOB DESCRIPTION", COLORS.primary);
      let tagX = ml + 2;
      checkPage(8);
      data.analysis.skills.add.forEach(s => {
        const sw = doc.getTextWidth(s) + 6;
        if (tagX + sw > pageWidth - mr) { y += 6; tagX = ml + 2; }
        tagX += addTag(s, tagX, "#bee3f8", COLORS.primary);
      });
      y += 7;
    }

    if (data.analysis.skills.remove?.length > 0) {
      addLabel("− REMOVE — NOT RELEVANT TO JD", COLORS.destructive);
      let tagX = ml + 2;
      checkPage(8);
      data.analysis.skills.remove.forEach(s => {
        const sw = doc.getTextWidth(s) + 6;
        if (tagX + sw > pageWidth - mr) { y += 6; tagX = ml + 2; }
        tagX += addTag(s, tagX, "#fed7d7", COLORS.destructive);
      });
      y += 7;
    }

    if (data.analysis.skills.reorganized) {
      addLabel("RECOMMENDED SKILL GROUPING");
      addBody(data.analysis.skills.reorganized, 2);
      y += 3;
    }

    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    if (data.appliedChanges.has("skills")) {
      doc.setTextColor(COLORS.accent);
      doc.text("✓ APPLIED TO RESUME", ml, y);
    } else {
      doc.setTextColor(COLORS.warning);
      doc.text("○ NOT YET APPLIED", ml, y);
    }
    y += 5;
  }

  // ============================
  // KEYWORD GAP ANALYSIS
  // ============================
  if (data.analysis.keywords) {
    addSectionTitle("4. KEYWORD GAP ANALYSIS");

    if (data.analysis.keywords.found_in_resume?.length > 0) {
      addLabel("✓ FOUND IN RESUME", COLORS.accent);
      let tagX = ml + 2;
      checkPage(8);
      data.analysis.keywords.found_in_resume.forEach(kw => {
        const kw_w = doc.getTextWidth(kw) + 6;
        if (tagX + kw_w > pageWidth - mr) { y += 6; tagX = ml + 2; }
        tagX += addTag(kw, tagX, "#c6f6d5", "#276749");
      });
      y += 7;
    }

    if (data.analysis.keywords.missing_critical?.length > 0) {
      addLabel("✗ MISSING — CRITICAL (MUST ADD)", COLORS.destructive);
      let tagX = ml + 2;
      checkPage(8);
      data.analysis.keywords.missing_critical.forEach(kw => {
        const kw_w = doc.getTextWidth(kw) + 6;
        if (tagX + kw_w > pageWidth - mr) { y += 6; tagX = ml + 2; }
        tagX += addTag(kw, tagX, "#fed7d7", COLORS.destructive);
      });
      y += 7;
    }

    if (data.analysis.keywords.missing_preferred?.length > 0) {
      addLabel("○ MISSING — PREFERRED (NICE TO HAVE)", COLORS.warning);
      let tagX = ml + 2;
      checkPage(8);
      data.analysis.keywords.missing_preferred.forEach(kw => {
        const kw_w = doc.getTextWidth(kw) + 6;
        if (tagX + kw_w > pageWidth - mr) { y += 6; tagX = ml + 2; }
        tagX += addTag(kw, tagX, "#fefcbf", "#975a16");
      });
      y += 7;
    }

    // Summary stats
    checkPage(12);
    const found = data.analysis.keywords.found_in_resume?.length || 0;
    const critical = data.analysis.keywords.missing_critical?.length || 0;
    const preferred = data.analysis.keywords.missing_preferred?.length || 0;
    const total = found + critical + preferred;
    const coverage = total > 0 ? Math.round((found / total) * 100) : 0;

    doc.setFillColor(COLORS.bg);
    doc.roundedRect(ml, y, cw, 12, 2, 2, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.dark);
    doc.text(`Keyword Coverage: ${coverage}%`, ml + 5, y + 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(COLORS.muted);
    doc.text(`${found} matched  |  ${critical} critical missing  |  ${preferred} preferred missing`, ml + 5, y + 9.5);
    y += 16;
  }

  // ============================
  // OVERALL TIPS
  // ============================
  if (data.analysis.overall_tips && data.analysis.overall_tips.length > 0) {
    addSectionTitle("5. ADDITIONAL RECOMMENDATIONS");
    data.analysis.overall_tips.forEach((tip, i) => {
      checkPage(6);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(COLORS.primary);
      doc.text(`${i + 1}.`, ml, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(COLORS.dark);
      addWrapped(tip, ml + 6, cw - 6, 4);
      y += 2;
    });
  }

  // ============================
  // CHANGES SUMMARY TABLE
  // ============================
  addSectionTitle("6. CHANGES APPLIED — SUMMARY");

  const rows = [
    { section: "Professional Summary", applied: data.appliedChanges.has("summary"), detail: data.analysis.summary ? "Rewritten to match JD" : "No changes suggested" },
    ...(data.analysis.experience || []).map((exp, i) => ({
      section: `Experience: ${exp.role}`,
      applied: data.appliedChanges.has(`exp-${i}`),
      detail: `${exp.improved_bullets?.length || 0} bullets improved, ${exp.missing_keywords_to_add?.length || 0} keywords flagged`,
    })),
    { section: "Skills", applied: data.appliedChanges.has("skills"), detail: data.analysis.skills ? `Keep ${data.analysis.skills.keep?.length || 0} | Add ${data.analysis.skills.add?.length || 0} | Remove ${data.analysis.skills.remove?.length || 0}` : "No changes suggested" },
  ];

  // Table header
  checkPage(10);
  doc.setFillColor(COLORS.primary);
  doc.rect(ml, y, cw, 7, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.white);
  doc.text("Section", ml + 3, y + 5);
  doc.text("Status", ml + 75, y + 5);
  doc.text("Details", ml + 100, y + 5);
  y += 7;

  rows.forEach((row, i) => {
    checkPage(8);
    const bgColor = i % 2 === 0 ? COLORS.bg : COLORS.white;
    doc.setFillColor(bgColor);
    doc.rect(ml, y, cw, 7, "F");

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.dark);
    const sectionText = doc.splitTextToSize(row.section, 65);
    doc.text(sectionText[0], ml + 3, y + 5);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(row.applied ? COLORS.accent : COLORS.warning);
    doc.text(row.applied ? "✓ Applied" : "○ Pending", ml + 75, y + 5);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.muted);
    const detailText = doc.splitTextToSize(row.detail, 70);
    doc.text(detailText[0], ml + 100, y + 5);
    y += 7;
  });

  // Final footer
  addFooter();

  return doc;
};

export const downloadOptimizationReport = (data: OptimizationReportData) => {
  const doc = generateOptimizationReport(data);
  const name = (data.resumeData.personalInfo.fullName || "resume").replace(/\s+/g, "_");
  doc.save(`${name}_optimization_report.pdf`);
};
